[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "next"